### PR TITLE
Switch to generic MariaDB container images

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by zackbradys** [comment]
is this planning on being merged? it would be really useful to use the generic images. @dirkmueller

**Comment by dirkmueller** [comment]
@zackbradys the maintenance of the helm chart was handed over to the RMT team. I don't know the state of this change (whether it has been released already) @felixsch  ?

**Comment by zackbradys** [comment]
thanks for the quick update @dirkmueller.

so is the helm chart no longer maintained/published from this repo?

**Comment by msmeissn** [comment]
rmt-mariadb is an alias for mariadb, so you are already getting the generic ones I would say

**Comment by zackbradys** [comment]
that is true, but if I'm running in the airgap, the helm chart will fail (by default), unless I pull those images separately and then move across the airgap, then deploy the helm chart.

if the images are the same as `mariadb`, why alias/retag them?

**Comment by dirkmueller** [comment]
> that is true, but if I'm running in the airgap, the helm chart will fail (by default), unless I pull those images separately, then move across the airgap, then deploy the helm chart. a lot of customers would already have the `mariadb` images loaded into their airgapped environments.
> 
> if the images are the same as `mariadb`, why alias/retag them? additionally, the helm chart is already using `nginx` not an alias/retag of `nginx` so to me it would make sense to have it for `mariadb` as well?

It is a transition. The intention was to go with `mariadb`, but we need to convert all our users first. One of the identified ones is RMT, which as you can see is still working on ingesting the change.

**Comment by dirkmueller** [comment]
> so is the helm chart no longer maintained/published from this repo?

It has never been published from this repo, it used to be maintained here. I don't know whether that is still the case here or whether the new team has moved it elsewhere already. I'm trying to find it out.

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I tested this pull request:**

- Checked the changes and if they make sense
- Ran the helm chart on a local cluster

Regarding ownership. As far as aware this helm chart is maintained by the SCC Team (RMT authors) and will eventually move to the RMT repository once the team gets time to work on this topic. Until then it will stay here

cheers,

Felix

**Pull request merged**
