### PR TITLE
Enable rmt chart run on air-gapped environments

### PR DESCRIPTION
**Pull request by rafaprata**
This PR attempts to enhance the rmt-chart to run on airgapped environments.

https://github.com/SUSE/rmt/issues/1171
https://github.com/SUSE/helm-charts/issues/11

### CODE REVIEW

**Comment by ngetahun** [comment]
[Enable air-gapped rmt deployment on kubernetes](https://trello.com/c/D5JZTQyL/3421-enable-air-gapped-rmt-deployment-on-kubernetes)

**Comment by josegomezr** [comment]
Hi @rafaprata,

Thanks for your contribution. Although this will fix the issue it opens a vector for unsupported (and _highly surprising_) behavior.

The first problem is: ConfigMap changes won't trigger a restart or a re-deployment of RMT.

The projected volume where the config map ends up mounted gets updated live and it expects that workloads react to this update.

Take as an example: [Prometheus helm charts][prom-helm]. In the deployment of prometheus there's an [optional container][prom-reload] whos only work is to listen for filesystem events triggered by [among other things] config maps and call the reload endpoint in prometheus itself to have the "live config reload" experience.

Should we enable this approach, the workload itself [rmt] needs to support listening to changes in the projected configmap, one way or another in order to react to the changes. Without it the only way is to make the change AND THEN restart the deployment [by doing whatever it takes as long as the rmt server pod gets to restart].

---

The second problem is that the configmap saves the bash entrypoint of the container image. in practice: this allows changing the container image contents pretty much silently.

**In the extremely optimistic scenario** this allows consumers of RMT to modify how RMT boots in ever creative ways, not necessarily aligning to what's supported, even if they fix the problem at hand.

By the same token it can allow for running effectively anything your heart (and the contained binaries in the rmt-* container images) allows. There's no readiness/startup/liveliness probes that would restart/back-off the startup of the container.

This is an easy vector for security problems. It just takes one silent config map change and a pod reboot to get a seemingly passive workload do very unexpected things. Worse of all, via the configmap the bug can be planted for *ages* until the restart is done and we get a cyber-security incident.

---

However, your solution does goes in a good direction, the behavior of the sync must be able to be influenced via `values.yaml` to allow Kubernetes operators to influence the abilities of the workload without compiling their own RMT image.

Instead of mounting an entrypoint [and thus changing the contents of the container], we should instead allow RMT have more cloud-friendly configuration inputs.

Making it react to environment vars is a first step in my eyes and if I read the docs from the [`config` gem RMT uses right now][config-v3] that should be easily achievable.

So after RMT can be influenced with env-vars we can introduce the appropriate `values.yaml` entries (maybe even add them to the `questions.yml` too for interactive installs on Rancher, those I don't fully know they work).

[config-v3]: https://github.com/rubyconfig/config/tree/3.0.0?tab=readme-ov-file#working-with-environment-variables
[prom-helm]: https://github.com/prometheus-community/helm-charts
[prom-reload]: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/deploy.yaml#L58C24-L112

**Review by josegomezr — DISMISSED** [review]
Forgot to leave the request changes mark, apologies.

**Review by ngetahun — APPROVED** [review]
LGTM! Will do follow up PRs to add suggestions from Jose

**Pull request merged**
